# Week 3 Lab - Basic Python Exercises

In this week's lab you will use what you have learnt from the Basic Python Programming notebook to solve some interesting problems using Python. The problems you will solve include:
1. Quadratic equation roots 
2. Sequence Generator
3. Basic data analysis on sentences

In order to run this notebook you need to install a python package first.
* lorem - this is a package which can be used to create random words, sentences, and paragraphs. More information [here](https://www.lipsum.com/)



This package will be installed by running the cells below. Let your demonstrator know if there are any errors with this step.

In [1]:
!pip install lorem

### Quadratic Equation Roots (15 Marks)

Create a function which takes in three integer inputs representing the coefficients $a$, $b$, and $c$ of the quadratic equation:
\begin{equation*}
ax^2+bx+c=0
\end{equation*}

The function should display the two roots of the equation ($x_1$ and $x_2$) according to:

\begin{equation*}
x_1 = \frac{-b+\sqrt{b^2-4ac}}{2a} \quad,
\quad x_2 = \frac{-b-\sqrt{b^2-4ac}}{2a}
\end{equation*}

For this exercise you will need to use the *complex* function in Python. Its functionality is shown in the cell below:

In [2]:
x1real = 5
x1comp = 6
x1 = complex(x1real,x1comp)

print(x1)

(5+6j)


You will also need the *sqrt()* function for finding the square root. This function is in the *math* python package. Lets import it in the cell below.

In [ ]:
import math

Complete the *findQuadraticRoots* function in the cell below to achieve the desired functionality

In [7]:
def findQuadraticRoots(a,b,c):
    '''
    Example 1:
           input => a = 5, b = 2, c = 1
           output -0.2+0.4j,-0.2-0.4j

    Example 2:
           input => a = 2, b = 5, c = -3
           output 0.5,-3
    '''
  
    x1 = 0
    x1real = 0
    x1comp = 0
    
    x2 = 0
    x2real = 0
    x2comp = 0
    
    #INSERT CODE HERE to achieve the desired functionality here
    
    #HINT - find the determinant first, and check if it is negative.
    #     - if the determinant is negative then find its absolute value,
    #       then find the real and complex parts of the solution
    #       and combine them using the complex function.
 

    
    
    
    
    return (x1,x2)

In [8]:
#ax2 + bx + c = 0
#a, b and c are real numbers and a is not equal to zer0
# Solve the quadratic equation ax**2 + bx + c = 0

# import complex math module
import cmath

a=int(input("enter a"))
b=int(input("enter b"))
c=int(input("enter c"))

# calculate the discriminant
d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

print('The solution are {0} and {1}'.format(sol1,sol2))

enter a2
enter b2
enter c1
The solution are (-0.5-0.5j) and (-0.5+0.5j)


Test your function using the cell below:

In [11]:
a = input('Enter the value of a: ')
a = float(a)
b = input('Enter the value of b: ')
b = float(b)
c = input('Enter the value of c: ')
c = float(c)

x1,x2 = findQuadraticRoots(a,b,c)
print('Quadratic Roots:')
print('sol1 = '+str(sol1))
print('sol2 = '+str(sol2))


Enter the value of a: 1
Enter the value of b: 2
Enter the value of c: 3
Quadratic Roots:
sol1 = (-0.5-0.5j)
sol2 = (-0.5+0.5j)


### Sequence Generator (15 Marks)

For this part, you are required to generate a sequence of numbers according to one of the following equations:
* eq1 :    $x_n = 2x(n-1)$
* eq2 :    $x_n = x(n-1)+x(n-2)$ 
* eq3 :    $x_n = x(n-1)-x(n-2)$ 

where $n$ is the nth element in the sequence.

Your function must allow for the first two numbers in the sequence to be specified, as well as the size of the sequence, and the method.
For example: 
* sequenceGenerator(0,1,10,'eq1') will generate the sequence 0,1,2,4,8,16,32,64,128,256
* sequenceGenerator(0,1,8,'eq2') will generate the sequence 0,1,1,2,3,5,8,13
* sequenceGenerator(3,5,7,'eq3') will generate the sequence 3,5,2,-3,-1,-4,-5

You will need the *numpy* python package to generate the sequence. We will import in it the cell below:
            



In [12]:
import numpy as np

In [13]:
# zeeshan see this function , logic idr hi lgni
def sequenceGenerator(firstNumber,secondNumber,sequenceSize,method):
    '''
    INPUTS:
        firstNumber - the first number in the sequence
        secondNumber - the second number in the sequence
        sequenceSize - the number of elements in the sequence (i.e the size of the generated sequence)
        method - the method used to generate the sequence. Can be one of three values:
               - 'eq1' for 2x(n−1)
               - 'eq2' for x(n−1)+x(n−2)
               - 'eq3' for x(n−1)−x(n−2)
    
    OUTPUTS:
        sequence - the generated sequence
    
    '''
    sequence = np.zeros(sequenceSize,dtype=np.int32)       #creates an array of size sequenceSize with all zeros
    
    #INSERT CODE HERE for assigning the first number input to the first position of the sequence
     
    sequence[0] = firstNumber
    #INSERT CODE HERE for assigning the second number input to the second position of the sequence
    sequence[1] = secondNumber      
    
    if(method == 'eq1'):
        #INSERT CODE HERE for generating the sequence using the 'eq1' method
        for i in range(2,sequenceSize):
            sequence[i] = 2*sequence[i-1]
#         x = 1
#         while x<= 5000:
#             print(x)
#             x *= 2 
        

    
        
        
        
    elif(method == 'eq2'):
        #INSERT CODE HERE for generating the sequence using the 'eq2' method
        for i in range(2,sequenceSize):
            sequence[i] = sequence[i-1] + sequence[i-2]
      
        
        
    elif(method == 'eq3'):
        #INSERT CODE HERE for generating the sequence using the 'eq3' method
        for i in range(2,sequenceSize):
            sequence[i] = sequence[i-1] - sequence[i-2]
  
        
    
    return sequence
        

In [14]:
s = np.zeros(5,dtype=np.int32)  
s[0]=1
s

array([1, 0, 0, 0, 0])

Test your function using the cell below

In [15]:
# zeeshan yha print krana h
sequence1 = sequenceGenerator(0,1,10,'eq1')
sequence2 = sequenceGenerator(3,7,20,'eq2')
sequence3 = sequenceGenerator(-1,5,7,'eq3')

print('Sequence Generated using eq1:')
print(sequence1)
print('Sequence Generated using eq2:')
print(sequence2)
print('Sequence Generated using eq3:')
print(sequence3)


Sequence Generated using eq1:
[  0   1   2   4   8  16  32  64 128 256]
Sequence Generated using eq2:
[    3     7    10    17    27    44    71   115   186   301   487   788
  1275  2063  3338  5401  8739 14140 22879 37019]
Sequence Generated using eq3:
[-1  5  6  1 -5 -6 -1]


### Basic Data Analysis on Sentences (20 Marks)

For this part, you are required to perform some basic data analysis on a randomly generated sentence. The sentence will be generated using the lorem package you installed at the beginning of this notebook. The analysis you will perform on this sentence should answer the following questions:
1. How many words are in the sentence?
2. What is the last word in the sentence?
3. What is the largest word(s) (most letters) in the sentence?
4. What is the smallest word(s) (least letters) in the sentence?
5. Which word(s) have 3 or more vowels?
6. What is the average word size in the sentence?

Your code should print the results of the data analysis in an easy to read way.

Lets see how to generate a random sentence using the lorem package in the cell below:



In [16]:
import lorem


sentence = lorem.sentence()
print(sentence)

Dolor sed amet etincidunt magnam.


If the generated sentence doesn't make sense to you, that's because it is pseudo-latin text. More information about it can be found [here](https://www.lipsum.com/).

The next useful thing we can do is convert the sentence into a list of individual words. We do this by using the *split()* function in python. First lets remove the full stop from the sentence.

In [17]:
splitByFullStop = sentence.split('.')    #we place the character we want to use to split the string (in this case a .)
print(splitByFullStop)

['Dolor sed amet etincidunt magnam', '']


This creates a list with two items: the part of the string before the full stop, and the remaining part of the string after the full stop (which in this case is nothing). Since we are only interested in the part of the string before the full stop, we just want the first item in the list.

In [18]:
sentence = splitByFullStop[0]
print(sentence)

Dolor sed amet etincidunt magnam


Now we can split the sentence into a list of individual words

In [19]:
words = sentence.split(' ')
print(words)

['Dolor', 'sed', 'amet', 'etincidunt', 'magnam']


Now that you know how to generate a random sentence (and split it into a list of words), create the *sentenceInsights* function in the cell below to answer the 6 questions mentioned earlier.

# Q1-How many words are in the sentence?

In [20]:
len(sentence)

32

<b> method1
 <b>

In [21]:
import re

res = len(re.findall(r'\w+', sentence))
print(res)

5


<b>method2<b>

In [22]:
res = len(sentence.split())
# total no of words
print ("The number of words in string are : " ,(res))


The number of words in string are :  5


# Q 2- Find the last word from sentence

In [23]:
res = list(sentence.split())
# total no of words
print ("The number of words in string are : " ,(res))

print ("The last word in sentence is : " ,(res[-1]))


The number of words in string are :  ['Dolor', 'sed', 'amet', 'etincidunt', 'magnam']
The last word in sentence is :  magnam


# Q3- What is the largest word(s) (most letters) in the sentence?


In [24]:
# just lenght
longest = len(max(re.findall(r'\S+',sentence), key = len))
print(longest)

10


In [65]:
# chracter itself
def findMaximum(sentence):
    li=sentence.split()
    li=list(li)
    op=[]
    for i in li:
        op.append(len(i))
    l=op.index(max(op))
    print (li[l])
findMaximum(sentence)

quiquia


# Q4- What is the Smallest word(s) (less letters) in the sentence?

In [66]:
def findMinimum(sentence):
    li=sentence.split()
    li=list(li)
    op=[]
    for i in li:
        op.append(len(i))
    l=op.index(min(op))
    print (li[l])
findMinimum(sentence)

Ut


# Q5- Which word(s) have 3 or more vowels?

In [27]:
vo=list(['a,e,i,o,u'])
print(words)
vo
sum=0

['Dolor', 'sed', 'amet', 'etincidunt', 'magnam']


In [28]:
for i in words:
    if vo==i:
        sum=sum+i
        
        
print(sum)    

0


In [71]:
print(words)
vowel=['a','e','i','o','u']
print(vowel)

['Dolor', 'sed', 'amet', 'etincidunt', 'magnam']
['a', 'e', 'i', 'o', 'u']


# Q6- What is the average word size in the sentence?

In [53]:

def main():
    print ("This program will calculate the average word length in a sentence")
    print
    s =sentence
    words = sentence.split()
    wordCount = len(words)
    sum = 0
    for word in words:
        ch = len(word)
        sum = sum + ch
    avg = sum / wordCount
    if avg is 1:
        print ("In the sentence '", s,"', the average word length is", avg,"letter.")
    else:
        print( "In the sentence '", s,"', the average word length is", avg,"letters.")
main()


This program will calculate the average word length in a sentence
In the sentence ' Dolor sed amet etincidunt magnam ', the average word length is 5.6 letters.


In [75]:
def sentenceInsights(sentence):
    '''
    EXAMPLE INPUT:
         Sed dolor numquam dolorem eius non modi quisquam.
         
    PRINT OUTPUT
        Analysis on the sentence: Sed dolor numquam dolorem eius non modi quisquam.
        Number of words : 8
        Last word : quisquam
        Largest word(s) : ['quisquam'] (8 letters)
        Smallest word(s) : ['sed','non'] (3 letters)
        Words with 3 or more vowels: ['numquam','dolorem','eius','quisquam'] (4 words)
        Average word size: 5 letters
 
    '''
    print("1")
    res = len(sentence.split())
    # total no of words
    print ("The number of words in string are : " ,(res))
    print("1 method 2")
    res = list(sentence.split())
    # total no of words
    print ("The number of words in string are : " ,(res))
    
    print("Ans 2")
    
    print ("The last word in sentence is : " ,(res[-1]))
    
    print("Ans 3")
    
   # chracter itself
    def findMaximum(sentence):
        li=sentence.split()
        li=list(li)
        op=[]
        for i in li:
            op.append(len(i))
        l=op.index(max(op))
        print ("Maximum Chracter in Sentence is",li[l])
    findMaximum(sentence)
    
    print("Ans 4")
    
    def findMinimum(sentence):
        li=sentence.split()
        li=list(li)
        op=[]
        for i in li:
            op.append(len(i))
        l=op.index(min(op))
        print ("Minimum Chracter in Sentence is",li[l])
    findMinimum(sentence)
    
    print(" Ans 5")
    
    vo=list(['a,e,i,o,u'])
    print(words)
    vo

    sum=0
    for i in words:
        if vo==i:
            sum=sum+i
        
        
    print(sum)  
    
    print("Ans 6")
        
    def main():
        print ("This program will calculate the average word length in a sentence")
        print
        s =sentence
        words = sentence.split()
        wordCount = len(words)
        sum = 0
        for word in words:
            ch = len(word)
            sum = sum + ch
            avg = sum / wordCount
        if avg is 1:
            print ("In the sentence '", s,"', the average word length is", avg,"letter.")
        else:
            print( "In the sentence '", s,"', the average word length is", avg,"letters.")
    main()


    


    #INSERT CODE HERE to generate the desired functionality. 
    # Note that the print output must be generated in this function so there will be no return statement for this function
    
    
    

Test your function using the cell below


In [76]:
sentence = lorem.sentence()
sentenceInsights(sentence)

1
The number of words in string are :  7
1 method 2
The number of words in string are :  ['Numquam', 'magnam', 'dolor', 'aliquam', 'non', 'est', 'porro.']
Ans 2
The last word in sentence is :  porro.
Ans 3
Maximum Chracter in Sentence is Numquam
Ans 4
Minimum Chracter in Sentence is non
 Ans 5
['Dolor', 'sed', 'amet', 'etincidunt', 'magnam']
0
Ans 6
This program will calculate the average word length in a sentence
In the sentence ' Numquam magnam dolor aliquam non est porro. ', the average word length is 5.285714285714286 letters.


**Well Done!** You have reached the end of the assessible material for this week's lab. 
If you would like to challenge yourself, try to use the *sentenceInsights* function on a randomly generated pararaph. To generate the paragraph, use lorem.paragraph()

*Hints:* 
* Split the paragraph into individual sentences,
* Use the *strip* function to remove any white spaces in the sentence,
* Pass each sentence to the *sentenceInsights* function using a for loop.

In [ ]:
paragraph  = lorem.paragraph()
print(paragraph)
